language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bladimirdev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bladimirdev/react-test npm test

after_success:
  - docker build -t bladimirdev/multi-client ./client
  - docker build -t bladimirdev/multi-server ./server
  - docker build -t bladimirdev/multi-worker ./worker
  - docker build -t bladimirdev/multi-nginx ./nginx
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push bladimirdev/multi-client
  - docker push bladimirdev/multi-server
  - docker push bladimirdev/multi-worker
  - docker push bladimirdev/multi-nginx
